#!/usr/bin/env python3
"""
Pull the written notes off the plan sheets and place them in model coordinates.

A set of drawings is not just geometry. Half of what a builder is being told is
in the text: "BEAM OVER TO ENG DETAILS", "STEPDOWN @170mm", "OPEN STRUCTURE WITH
TREATED TIMBER LANDING AS STEPS IF REQUIRED", "BALUSTRADE @1025mm HIGH AS
SELECTED". None of that survives into a 3D model of rooms and walls, and all of
it is the part a client asks about when they look at the render.

So it is carried across as its own layer. Every note keeps the position it has
on the sheet, converted to model metres with the registration in PLANS.md, and
the overlay puts it back over the level it belongs to.

Filtering, in order:
  · anything outside the building envelope is site or title-block text;
  · pure dimension strings are already drawn by the measurement overlay;
  · room names are already drawn as room labels;
  · window and door schedule codes (AW 0409, CSD 720) are tagged rather than
    dropped — they are what the joinery is, and worth being able to see.

    python3 tools/plannotes.py samples/SK1.pdf > src/lib/model/planNotes.ts
"""
import argparse
import json
import re
import sys

PT_PER_M = 28.3465
# (page index, origin x, origin y) per floor — see PLANS.md
REGISTRATION = {0: (1, 172.60, 593.10), 1: (2, 166.67, 568.67)}
ENVELOPE = (-1.0, 29.0, -1.0, 12.0)

ROOM_WORDS = {
    'LIVING', 'KITCHEN', 'FAMILY', 'DINING', 'MEALS', 'ALFRESCO', 'PANTRY', 'WIP',
    'PDR', 'POWDER', 'LAUNDRY', "L'DRY", 'GARAGE', 'DOUBLE GARAGE', 'GUEST', 'ENTRY',
    'PORCH', 'HALL', 'BED', 'BED 2', 'BED 4', 'BED 5', 'STUDY', 'SITTING ROOM',
    'PRINCIPAL SUITE', 'BALCONY', 'BATH', 'ENS', 'ENS 1', 'ENS 2', 'WIR', 'WIR 1',
    'WIR 2', 'WIL', 'ROBE', 'ALCOVE', 'BED 2 BATH', 'BED 4 WIR 2', 'WIR 1 STUDY',
}
# what kind of thing the note is about, most specific pattern first
KINDS = [
    ('opening', r'\b(?:AF|AS|AW|ASD|CSD|AF\d)[\s\-]?\d'),
    ('level',   r'FFL|AHD|STEPDOWN|FALL\b|RL\s'),
    ('structure', r'BEAM|SHS|POST|LINTEL|TRUSS|CAPPING|LINE OF DWELLING'),
    ('safety',  r'BALUSTRADE|HANDRAIL|SMOKE|INTERLOCK'),
    ('service', r'D\.P|S\.P|TAP|W\.M\.|PROV|DRYER|RANGEHOOD|A/C|WATER TANK|SUMP|DRAIN|CHUTE|FAN|OVERFLOW|DUCTED|MONORAIL'),
    ('joinery', r'NICHE|LINEN|MIRROR|SHR|BATH|VANITY|V\s?\d{3}|BENCH|BULKHEAD|LAMINATED|END PANEL|C\.L'),
]
DIMENSION = re.compile(r"^[\d,.\sxX×@Ø/\-–]+$")


def kind_of(text: str) -> str:
    up = text.upper()
    for name, pat in KINDS:
        if re.search(pat, up):
            return name
    return 'note'


def notes(pdf):
    import fitz                                         # PyMuPDF, local tooling only
    doc = fitz.open(pdf)
    x0e, x1e, z0e, z1e = ENVELOPE
    out = []
    for floor, (page, ox, oz) in REGISTRATION.items():
        for b in doc[page].get_text('blocks'):
            text = ' '.join(b[4].split())
            if len(text) < 4:
                continue
            if DIMENSION.fullmatch(text):
                continue
            if text.upper() in ROOM_WORDS:
                continue
            x = ((b[0] + b[2]) / 2 - ox) / PT_PER_M
            z = (oz - (b[1] + b[3]) / 2) / PT_PER_M
            if not (x0e < x < x1e and z0e < z < z1e):
                continue
            out.append({
                'id': f'n{floor}_{len(out)}',
                'floor': floor,
                'x': round(x, 2), 'z': round(z, 2),
                'text': text,
                'kind': kind_of(text),
            })
    return out


HEAD = '''/**
 * Written notes lifted off SK1, positioned in model metres.
 *
 * GENERATED by tools/plannotes.py — do not edit by hand; re-run the tool.
 *
 * Half of what a drawing tells a builder is text, and none of it survives into
 * a model made of rooms and walls. "BEAM OVER TO ENG DETAILS" is the reason a
 * ceiling steps down; "STEPDOWN @170mm" is the reason the garage slab is lower
 * than the house; "OPEN STRUCTURE WITH TREATED TIMBER LANDING AS STEPS IF
 * REQUIRED" is a whole element that only exists as a sentence. Carrying the
 * notes across as their own layer means the render can be checked against what
 * the drawing actually says, not just against its lines.
 */
export type NoteKind = 'opening' | 'level' | 'structure' | 'safety' | 'service' | 'joinery' | 'note';
export interface PlanNote {
  id: string; floor: 0 | 1;
  /** position on plan, in model metres */
  x: number; z: number;
  text: string;
  kind: NoteKind;
}

export const NOTE_LABEL: Record<NoteKind, string> = {
  opening: 'Window & door schedule',
  level: 'Levels and falls',
  structure: 'Structure',
  safety: 'Safety',
  service: 'Services',
  joinery: 'Joinery & fixtures',
  note: 'General notes',
};

export const PLAN_NOTES: PlanNote[] = '''


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('pdf')
    a = p.parse_args()
    try:
        rows = notes(a.pdf)
    except ImportError:
        print('needs PyMuPDF: pip install --break-system-packages pymupdf', file=sys.stderr)
        return 1
    body = ',\n  '.join(json.dumps(r, ensure_ascii=False) for r in rows)
    print(HEAD + '[\n  ' + body + ',\n];')
    print(f'\n// {len(rows)} notes', file=sys.stderr)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
